cypress-api.html, index.html, todo.html, utilities.html files fixed
Tny6918/g2-cypress-sandbox pull request #1
Opened 2024-01-07 11:57 UTC by Tny6918

added data-test attributes to the dropdown li elements

2024-01-07 12:48 UTC, SanitarskyiDmytro requested changes
Все що зроблено - правильно, але покрито не всі сторінки. Загалом їх 21 шт має бути

2024-01-08 08:37 UTC, SanitarskyiDmytro approved these changes
поверніть class="active" в ті теги де він був і можна мерджити)

2024-01-08 08:37 UTC, SanitarskyiDmytro commented on app/commands/actions.html
> -              <li class="active"><a href="/commands/actions">Actions</a></li>
Всюди де ви цей клас видалили потрібно повернути його назад)

2024-01-09 19:54 UTC, DmytroSanitarskyi approved these changes

2024-01-10 17:25 UTC, merged